### ISSUE TITLE
Heroes unplayable after Gmod update

### ISSUE THREAD

**Issue by BenitoTV** [TTT-2/ttt2-heroes#6]
I'm not sure since when this problem exists, but we have played TTT2 Heroes for the first time since the latest Gmod update and now it doesn't work properly. The equipment menu (when you scroll and see your weapons) disappears when someone places his crystal. The ability-meter also isn't visible. This is the error that comes when placing a crystal:

![image](https://github.com/TTT-2/ttt2-heroes/assets/111009199/9bca97d9-489a-4733-9a20-0e7bc22b9aca)

This error is similar to the error that makes TTT2 unplayable with the necromancer and Boom Body.

**Comment by TimGoll** [comment]
Looks like you're using an outdated version of TTT2?

**Comment by DocHudge** [comment]
Looks like an old version isn't it ?
